site_name: My Docs
theme:
  name: material
  language: ja
  features:
    - search.suggest
    - search.highlight
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  # - pymdownx.tilde
plugins:
  - search
# copyright: "Copyright © Tokyo Metropolitan Industrial Technology Research institute"
nav: 
  - Home: index.md
  - Gazeboの使い方: gazeboの使い方.md
  - Gazeboでのロボットの作り方: gazeboでのロボットの作り方.md
  - GazeboとROSの連携方法: GazeboとROSの連携方法.md
  - 各種インストール方法: 
    - ①macOSに直接インストールして動かす: homebrew_install.md
    - ②仮想マシン(UTM)上のUbuntuで動かす: utm_install.md
    - ③macOSのDocker上のUbuntuで動かす: docker_install.md
    - ④仮想マシン(UTM)のDocker上のUbuntuで動かす: utm_docker_install.md
  - Gazeboの参考ページ: gazebo_advance.md 
  - 各種ロボット: 
    - Kinova Gen3 Lite: kinova_gen3_lite.md