site_name: My Docs
theme:
  name: material
  language: ja
  features:
    - search.suggest
    - search.highlight
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  # - pymdownx.tilde
plugins:
  - search
# copyright: "Copyright © Tokyo Metropolitan Industrial Technology Research institute"
nav: 
  - Home: index.md
  - あ: 
    - い: test2.md
    - う: test1.md